[package]
name = "yeehaw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crossterm = {version = "^0.27.0", features = ["event-stream"]}
anyhow = "^1.0.0"
rand = "^0.8.0"
bincode = {version = "2.0.0-rc.3",  features = ["serde"] }
