[workspace]
resolver = "2"
members = [
    "yeehaw",
    "yeehaw_derive",
    "vt100_yh",
]

[workspace.package]
include = ["src/**/*.rs", "tests/**/*.rs", "LICENSE", "README.md"]
edition = "2021"

[workspace.dependencies]

