language = "Rust"

project_name = "yeehaw"

otel_enabled = true

## Optional: Connect kwaak to tavily to enable it to search the web
tavily_api_key = "env:TAVILY_API_KEY"
github_api_key = "env:KWAAK_GITHUB_TOKEN"
openai_api_key = "env:KWAAK_OPENAI_API_KEY"

tool_executor = "docker"

[commands]
test = "cargo test -p yeehaw --no-fail-fast --color=never"
coverage = "cargo llvm-cov nextest -p yeehaw --no-clean --summary-only"
lint_and_fix = "cargo clippy --fix --allow-dirty --allow-staged && cargo fmt"

[git]
owner = "bogzbonny"
repository = "yeehaw"
main_branch = "main"

[llm.indexing]
provider = "OpenAI"
prompt_model = "gpt-4o-mini"

[llm.query]
provider = "OpenAI"
prompt_model = "gpt-4o"

[llm.embedding]
provider = "OpenAI"
embedding_model = "text-embedding-3-large"

[docker]
dockerfile = "Dockerfile"
