// all 128 box drawing characters:
// ─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋╌╍╎╏═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬╭╮╯╰╱╲╳╴╵╶╷╸╹╺╻╼╽╾╿

use crate::{BoxDrawingCh, Dashes, SideAttribute};

impl BoxDrawingCh {
    /// gets the BoxDrawingCh from the character provided,
    /// if the character is not a box drawing character, returns None
    pub fn get_from_char(c: char) -> Option<BoxDrawingCh> {
        // giant match statement of all 125 box drawing characters (excluding the 3 diagonal characters)
        // also consider the Space to be a box drawing character
        // so in total there should be 126 match arms
        // verification number of lines:
        //   126*8==1008
        match c {
            ' ' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '─' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '━' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '│' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┃' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┄' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Triple),
            }),
            '┅' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Triple),
            }),
            '┆' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: Some(Dashes::Triple),
            }),
            '┇' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: Some(Dashes::Triple),
            }),
            '┈' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Quadruple),
            }),
            '┉' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Quadruple),
            }),
            '┊' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: Some(Dashes::Quadruple),
            }),
            '┋' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: Some(Dashes::Quadruple),
            }),
            '┌' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┍' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┎' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┏' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┐' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┑' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┒' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┓' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '└' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┕' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┖' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┗' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┘' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┙' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┚' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┛' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '├' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┝' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┞' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┟' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┠' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┡' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┢' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┣' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┤' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┥' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┦' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┧' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┨' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┩' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┪' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┫' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┬' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┭' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┮' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┯' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┰' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┱' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┲' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┳' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '┴' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┵' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┶' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┷' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┸' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┹' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┺' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┻' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '┼' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┽' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┾' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '┿' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╀' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╁' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╂' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╃' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╄' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╅' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╆' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╇' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╈' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╉' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╊' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╋' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╌' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Double),
            }),
            '╍' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: Some(Dashes::Double),
            }),
            '╎' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: Some(Dashes::Double),
            }),
            '╏' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: Some(Dashes::Double),
            }),
            '═' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '║' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╒' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╓' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╔' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╕' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╖' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╗' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╘' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╙' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╚' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╛' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╜' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╝' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╞' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╟' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╠' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╡' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╢' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╣' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: None,
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╤' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╥' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╦' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: None,
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╧' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╨' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╩' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Double),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╪' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╫' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╬' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Double),
                right: Some(SideAttribute::Double),
                up: Some(SideAttribute::Double),
                down: Some(SideAttribute::Double),
                curved: false,
                dashes: None,
            }),
            '╭' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: None,
                down: Some(SideAttribute::Thin),
                curved: true,
                dashes: None,
            }),
            '╮' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: None,
                down: Some(SideAttribute::Thin),
                curved: true,
                dashes: None,
            }),
            '╯' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: Some(SideAttribute::Thin),
                down: None,
                curved: true,
                dashes: None,
            }),
            '╰' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: Some(SideAttribute::Thin),
                down: None,
                curved: true,
                dashes: None,
            }),
            '╴' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: None,
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╵' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╶' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╷' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: None,
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),
            '╸' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: None,
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╹' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: None,
                curved: false,
                dashes: None,
            }),
            '╺' => Some(BoxDrawingCh {
                left: None,
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╻' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: None,
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╼' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thin),
                right: Some(SideAttribute::Thick),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╽' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thin),
                down: Some(SideAttribute::Thick),
                curved: false,
                dashes: None,
            }),
            '╾' => Some(BoxDrawingCh {
                left: Some(SideAttribute::Thick),
                right: Some(SideAttribute::Thin),
                up: None,
                down: None,
                curved: false,
                dashes: None,
            }),
            '╿' => Some(BoxDrawingCh {
                left: None,
                right: None,
                up: Some(SideAttribute::Thick),
                down: Some(SideAttribute::Thin),
                curved: false,
                dashes: None,
            }),

            // If no match found, return None
            _ => None,
        }
    }
}
